#!/bin/bash
#SBATCH --job-name=pi					# Job name
#SBATCH --output=output_%j.log          # Output file (with job ID)
#SBATCH --error=error_%j.log            # Error file (with job ID)
#SBATCH --time=00:30:00                 # Time limit hrs:min:sec
#SBATCH --ntasks=1						# Number of tasks
#SBATCH --cpus-per-task=20				# Number of CPUs per task
#SBATCH --exclusive						# do not share node with somebody else

module load gcc

make clean
make

#!/bin/bash

THREADS=(1 2 4 8 16 20) 

for i in "${THREADS[@]}"; do
    export OMP_NUM_THREADS=$i
        echo "OMP_NUM_THREADS = $OMP_NUM_THREADS"
	./pi.exe
    done
done
