#!/bin/bash
#SBATCH --job-name=managerworker
#SBATCH --output=output_%j.log          # Output file (with job ID)
#SBATCH --error=error_%j.log            # Error file (with job ID)
#SBATCH --time=00:30:00                 # Time limit hrs:min:sec
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --exclusive

module load python py-pip openmpi
conda init bash 
conda activate project5_env

PROCESSES=(2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) 
TASKS=(50 100)

echo "======== STRONG SCALING ========="
for i in "${PROCESSES[@]}"; do
	for j in "${TASKS[@]}"; do
		mpiexec -n $i python manager_worker.py 4001 4001 $j >> output.log
	done
done
